-- Tilføjer arter/sorter fra Morbærgård_dyrkningsopslag_Perkins_2026.xlsx
-- der ikke allerede findes i afgrødedatabasen. Se Claude-samtale for kortlægning.
BEGIN;

WITH new_family AS (
  INSERT INTO crop_families (name_da, scientific_name)
  VALUES ('Pileurtfamilien', 'Polygonaceae')
  RETURNING id, name_da
),
new_species AS (
  INSERT INTO crop_species (family_id, name_da, scientific_name, plant_type)
  SELECT COALESCE(nf.id, ef.id), v.name_da, v.scientific_name, v.plant_type
  FROM (VALUES
    ('Asiatisk kål', 'Brassica rapa', 'Korsblomstfamilien', 'etårig'),
    ('Kinakål', 'Brassica rapa subsp. pekinensis', 'Korsblomstfamilien', 'etårig'),
    ('Majroe', 'Brassica rapa subsp. rapa', 'Korsblomstfamilien', 'etårig'),
    ('Mizuna', 'Brassica rapa var. nipposinica', 'Korsblomstfamilien', 'etårig'),
    ('Pak choi', 'Brassica rapa subsp. chinensis', 'Korsblomstfamilien', 'etårig'),
    ('Rabarber', 'Rheum × hybridum', 'Pileurtfamilien', 'flerårig'),
    ('Sennep (bladsennep)', 'Brassica juncea', 'Korsblomstfamilien', 'etårig')
  ) AS v(name_da, scientific_name, family_name, plant_type)
  LEFT JOIN new_family nf ON v.family_name = nf.name_da
  LEFT JOIN crop_families ef ON v.family_name = ef.name_da
  RETURNING id, name_da
)
INSERT INTO crop_varieties (
  species_id, name, synonyms, row_spacing_cm, plant_spacing_cm,
  days_to_harvest_transplant, days_to_harvest_direct, weeks_to_transplant,
  direct_sow, indoor_propagation, description, care_notes, is_system_variety
)
SELECT COALESCE(ns.id, es.id), vv.variety_name, vv.latin, vv.row_sp, vv.plant_sp,
       vv.days_t, vv.days_d, vv.weeks_tp, vv.direct_sow, vv.indoor_prop, vv.descr, vv.care, true
FROM (VALUES
    ('Agurk', 'Armenian Yard Long', 'Cucumis melo var. flexuosus', NULL, NULL, NULL, NULL, NULL, false, true, 'Lysgrøn og riflet; ofte høstet ca. 30 cm, kan blive 40–60 cm. Sprød, saftig og mild med et strejf af melon. Behold hanblomster og hjælp evt. bestøvningen. Albinus angiver 8–10 frø/pose.', 'Høstform: Plukkes løbende | Udplantning/timing: Udplant i lun tunnel omkring juni | Kilde: https://albinusfro.dk/shop/26-koekkenhaven/995-agurk-ltbrgtarmenian-yard-long-ltbrgtltigtcucumis-melo-var-flexuosusltigt/'),
    ('Agurk', 'Suyo Long', 'Cucumis sativus', NULL, 45, 51, NULL, 4, false, true, 'Lang, riflet kinesisk agurk, op til ca. 38 cm. Sød smag, uden bitterhed; opbinding giver mere lige frugter. Johnny’s angiver 61 dage fra direkte såning, ca. 51 fra udplantning og 30 frø/pose.', 'Høstform: Plukkes løbende | Udplantning/timing: Når jord og luft er varmet op | Kilde: https://www.johnnyseeds.com/vegetables/cucumbers/specialty-cucumbers/suyo-long-organic-cucumber-seed-333G.11.html'),
    ('Agurk', 'Telegraph Improved', 'Cucumis sativus', NULL, 45, NULL, NULL, NULL, false, true, 'Ældre engelsk sort; slanke mørkegrønne frugter på ca. 25–35 cm. Mild smag, kræver opbinding og jævn vanding. Plantetorvet angiver drivhus som velegnet.', 'Høstform: Plukkes løbende | Udplantning/timing: Udplant i varm tunnel efter kulde | Kilde: https://www.plantetorvet.dk/oeko-agurk-telegraph-improved-37894/'),
    ('Agurk', 'Kaikura F1', 'Cucumis sativus', NULL, 40, NULL, NULL, NULL, false, true, 'Lille mørkegrøn snackagurk på 5–8 cm; sprød med frisk, mild smag. Plukkes ofte. Plantetorvet angiver ca. 5 frø/pose.', 'Høstform: Plukkes ofte ved 5–8 cm | Udplantning/timing: Udplant i lun, beskyttet jord | Kilde: https://www.plantetorvet.dk/p/96736/dyrk-selv-froe-oeko-snackagurk-kaikura-f1-cucumis-sativus-kaikura-f1'),
    ('Asiatisk kål', 'Hon Tsai Tai', 'Brassica rapa', 25, 30, 45, NULL, NULL, false, true, 'Lilla blomsterstilke og knopper med mild sennepssmag. Høst spæde skud flere gange; anvend rå eller let tilberedt.', 'Kilde: https://www.johnnyseeds.com/vegetables/greens/asian-greens/hon-tsai-tai-asian-green-seed-138.26.html'),
    ('Asiatisk kål', 'Tatsoi', 'Brassica rapa', 25, 30, 45, NULL, NULL, false, true, NULL, NULL),
    ('Aubergine', 'Louisiana Long Green', 'Solanum melongena', NULL, 45, 75, NULL, NULL, NULL, NULL, 'Lange, slanke, let buede lysegrønne frugter. Fast kød, sød og nøddeagtig smag; pluk inden ca. 20 cm.', 'Kilde: https://albinusfro.dk/shop/26-koekkenhaven/863-aubergine-ltbrgtlouisiana-long-greenltbrgt-ltigtsolanum-melongenaltigt/'),
    ('Spinat', 'Seaside F1', 'Spinacia oleracea', NULL, 5, NULL, NULL, 3, false, true, 'Glatbladet spinat, velegnet til høst som babyblade. Babyspinat er et høststadium, ikke en særskilt art.', 'Høstform: Bladspinat | Udplantning/timing: Udplantning | Kilde: https://www.johnnyseeds.com/vegetables/spinach/smooth-leaf-spinach/seaside-f1-spinach-seed-3927.56.html'),
    ('Mangold/Bladbede', 'Bright Lights', 'Beta vulgaris (Cicla Group)', 25, 30, NULL, NULL, NULL, false, true, 'Farveblanding med gule, rosa, orange, røde og hvide stængler; mildere smag end almindelig bladbede.', 'Kilde: https://www.johnnyseeds.com/vegetables/swiss-chard/bright-lights-swiss-chard-seed-703D.54.html'),
    ('Broccoli', 'Blue Wind', 'Brassica oleracea (Italica Group)', 25, 45, 65, NULL, NULL, false, true, NULL, 'Høstform: Hoved og senere sideskud | Udplantning/timing: Udplantning'),
    ('Broccoli', 'Gypsy', 'Brassica oleracea (Italica Group)', 25, 45, 65, NULL, NULL, false, true, 'Ensartede kuplede hoveder; god varmetolerance og sideskud efter hovedhøsten.', 'Høstform: Hoved og senere sideskud | Udplantning/timing: Udplantning | Kilde: https://www.johnnyseeds.com/vegetables/broccoli/standard-broccoli/gypsy-f1-broccoli-seed-2413.54.html'),
    ('Broccoli', 'Imperial', 'Brassica oleracea (Italica Group)', 25, 45, 65, NULL, NULL, false, true, NULL, 'Høstform: Hoved og senere sideskud | Udplantning/timing: Start: 10. april; Så/plant: 1. maj'),
    ('Broccoli', 'Puntoverde', 'Brassica oleracea (Italica Group)', 25, 45, 65, NULL, NULL, false, true, NULL, 'Høstform: Hoved og senere sideskud | Udplantning/timing: Start: 10. april; Så/plant: 1. maj'),
    ('Bønne', 'Amethyst', 'Phaseolus vulgaris', 45, 10, 55, NULL, NULL, false, true, 'Slanke lilla buskbønner med god smag rå eller kogte; bælgene bliver grønne ved tilberedning.', 'Kilde: https://www.johnnyseeds.com/vegetables/beans/bush-beans/amethyst-bean-seed-3011.11.html'),
    ('Bønne', 'Faraday', 'Phaseolus vulgaris', 45, 10, 55, NULL, NULL, false, true, NULL, NULL),
    ('Bønne', 'Orinocco', 'Phaseolus vulgaris', 45, 10, 55, NULL, NULL, false, true, NULL, NULL),
    ('Chili', 'Jalapeño', 'Capsicum annuum', NULL, 40, 75, NULL, NULL, NULL, NULL, 'Kødfuld chili med moderat styrke; frugterne kan bruges grønne eller modne røde og røges til chipotle.', 'Kilde: https://albinusfro.dk/shop/26-koekkenhaven/1400-chili-ltbrgtjalapentildeoltbrgtltigtcapsicum-annuumltigt/'),
    ('Fennikel', 'Orazio', 'Foeniculum vulgare', 25, 20, 80, NULL, NULL, false, true, 'Knoldfennikel: saftige lyse knolde med karakteristisk mild anisduft; et interessant valg til rå og tilberedt brug.', 'Perkins: Tabellen siger 20 cm i rækken; den løbende tekst siger 15 cm. | Høstform: Unge, små knolde | Udplantning/timing: Start: 10. april; Så/plant: 1. maj | Kilde: https://www.johnnyseeds.com/vegetables/fennel/orazio-f1-fennel-seed-3273.56.html'),
    ('Forårsløg', 'Lilia', 'Allium sp. (artsplacering afhænger af sort)', 25, 15, 60, NULL, NULL, false, true, NULL, 'Perkins: Tabellen siger 15 cm, afgrødenoten 25 cm; paperpot-alternativ 5 cm. | Høstform: Høstes i bundter | Udplantning/timing: Start: 1. april; Så/plant: 1. maj'),
    ('Forårsløg', 'White Lisbon', 'Allium sp. (artsplacering afhænger af sort)', 25, 15, 60, NULL, NULL, false, true, 'Klassisk mildt forårsløg med hvide skafter og grøn top; høstes ungt.', 'Perkins: Tabellen siger 15 cm, afgrødenoten 25 cm; paperpot-alternativ 5 cm. | Høstform: Høstes i bundter | Udplantning/timing: Udplantning | Kilde: https://floreagarden.com/en-dk/products/seeds-spring-onion-white-lisbon'),
    ('Glaskål (knudekål)', 'Corridor', 'Brassica oleracea (Gongylodes Group)', 25, 20, NULL, NULL, NULL, false, true, NULL, 'Høstform: Høst knold før trævlet | Udplantning/timing: Udplantning'),
    ('Glaskål (knudekål)', 'Kolibri', 'Brassica oleracea (Gongylodes Group)', 25, 20, NULL, NULL, NULL, false, true, 'Dyb lilla skal og hvidt, sprødt næsten trævlefrit kød. Høstes typisk ved ca. 7–8 cm.', 'Høstform: Høst knold før trævlet | Udplantning/timing: Udplantning | Kilde: https://www.johnnyseeds.com/vegetables/kohlrabi/fresh-market-kohlrabi/kolibri-organic-f1-kohlrabi-seed-320G.html'),
    ('Glaskål (knudekål)', 'Winner', 'Brassica oleracea (Gongylodes Group)', 25, 20, NULL, NULL, NULL, false, true, NULL, 'Høstform: Høst knold før trævlet | Udplantning/timing: Udplantning'),
    ('Peberfrugt', 'California Wonder', 'Capsicum annuum', NULL, 40, 75, NULL, NULL, NULL, NULL, 'Klassisk blokformet sød peber, som kan høstes grøn eller modnes rød; grøn og rød er høststadier for samme frugt.', 'Kilde: https://www.laubjergs-havecenter.dk/en/products/paprika-california-wonder'),
    ('Grønkål', 'Black Magic', 'Brassica oleracea (Acephala Group)', 25, 30, 60, NULL, NULL, false, true, 'Mørke, lange, smalle Toscano-blade; pæn opret vækst til bundter.', 'Høstform: Pluk yderblade i 5–8 uger | Udplantning/timing: Udplantning | Kilde: https://www.johnnyseeds.com/vegetables/kale/black-magic-organic-kale-seed-3531G.54.html'),
    ('Grønkål', 'Redbor', 'Brassica oleracea (Acephala Group)', 25, 30, 60, NULL, NULL, false, true, NULL, 'Høstform: Pluk yderblade i 5–8 uger | Udplantning/timing: Udplantning'),
    ('Grønkål', 'Starbor', 'Brassica oleracea (Acephala Group)', 25, 30, 60, NULL, NULL, false, true, NULL, 'Høstform: Pluk yderblade i 5–8 uger | Udplantning/timing: Udplantning'),
    ('Grønkål', 'Toscano', 'Brassica oleracea (Acephala Group)', 25, 30, 60, NULL, NULL, false, true, NULL, 'Høstform: Pluk yderblade i 5–8 uger | Udplantning/timing: Udplantning'),
    ('Grønkål', 'Winterbor', 'Brassica oleracea (Acephala Group)', 25, 30, 60, NULL, NULL, false, true, NULL, 'Høstform: Pluk yderblade i 5–8 uger | Udplantning/timing: Start: 29. marts; Så/plant: 19. april'),
    ('Løg', 'Patterson F1', 'Allium cepa', 25, 25, NULL, NULL, NULL, false, true, 'Gult løg af lagringstypen. Beregn løg som antal og vægt ved høst; udbytte varierer med størrelse og lagring.', 'Høstform: Engangshøst / opbevaring | Udplantning/timing: Udplantning | Kilde: https://www.johnnyseeds.com/vegetables/onions/full-size-onions/patterson-pelleted-f1-onion-seed-2521JP.54.html'),
    ('Gulerod', 'Bolero', 'Daucus carota', 10, 2.54, NULL, 70, NULL, true, false, NULL, 'Perkins: Babygulerødder kan sås i 12 rækker i stedet for 6. | Høstform: Høst med top | Udplantning/timing: Så/plant: 9. maj'),
    ('Gulerod', 'Gold Nugget', 'Daucus carota', 10, 2.54, NULL, 70, NULL, true, false, NULL, 'Perkins: Babygulerødder kan sås i 12 rækker i stedet for 6. | Høstform: Høst med top | Udplantning/timing: Direkte såning'),
    ('Gulerod', 'Malbec', 'Daucus carota', 10, 2.54, NULL, 70, NULL, true, false, NULL, 'Perkins: Babygulerødder kan sås i 12 rækker i stedet for 6. | Høstform: Høst med top | Udplantning/timing: Direkte såning'),
    ('Gulerod', 'Myashigii', 'Daucus carota', 10, 2.54, NULL, 70, NULL, true, false, NULL, 'Perkins: Babygulerødder kan sås i 12 rækker i stedet for 6. | Høstform: Høst med top | Udplantning/timing: Direkte såning'),
    ('Gulerod', 'Purple Haze', 'Daucus carota', 10, 2.54, NULL, 70, NULL, true, false, 'Lilla yderside og orange kerne giver et markant snit. Smag og farve gør den interessant til frisk servering.', 'Perkins: Babygulerødder kan sås i 12 rækker i stedet for 6. | Høstform: Høst med top | Udplantning/timing: Så/plant: 1. maj | Kilde: https://www.johnnyseeds.com/vegetables/carrots/main-crop-carrots/purple-haze-f1-carrot-seed-2680.html'),
    ('Gulerod', 'Rainbow', 'Daucus carota', 10, 2.54, NULL, 70, NULL, true, false, NULL, 'Perkins: Babygulerødder kan sås i 12 rækker i stedet for 6. | Høstform: Høst med top | Udplantning/timing: Direkte såning'),
    ('Gulerod', 'Sugarsnax', 'Daucus carota', 10, 2.54, NULL, 70, NULL, true, false, NULL, 'Perkins: Babygulerødder kan sås i 12 rækker i stedet for 6. | Høstform: Høst med top | Udplantning/timing: Så/plant: 24. maj'),
    ('Gulerod', 'White Satin', 'Daucus carota', 10, 2.54, NULL, 70, NULL, true, false, NULL, 'Perkins: Babygulerødder kan sås i 12 rækker i stedet for 6. | Høstform: Høst med top | Udplantning/timing: Direkte såning'),
    ('Gulerod', 'YaYa', 'Daucus carota', 10, 2.54, NULL, 70, NULL, true, false, NULL, 'Perkins: Babygulerødder kan sås i 12 rækker i stedet for 6. | Høstform: Høst med top | Udplantning/timing: Direkte såning'),
    ('Gulerod', 'Yellowbunch', 'Daucus carota', 10, 2.54, NULL, 70, NULL, true, false, NULL, 'Perkins: Babygulerødder kan sås i 12 rækker i stedet for 6. | Høstform: Høst med top | Udplantning/timing: Direkte såning'),
    ('Hvidløg', 'German Extra Hardy', 'Allium sativum', 25, 15, 240, NULL, NULL, false, true, 'Hårdnakket hvidløgstype, der sælges som sættehvidløg. Pillede indkøbte fed er en købsform, ikke i sig selv egnet plantemateriale.', 'Høstform: Sommerhøst efter brunfarvning | Udplantning/timing: Fed sættes sent efterår | Kilde: https://www.johnnyseeds.com/vegetables/garlic/german-extra-hardy-certified-naturally-grown-garlic-bulbs-3535.29.html'),
    ('Jordbær', 'Mara des Bois', 'Fragaria × ananassa', 30, 30, NULL, NULL, NULL, NULL, NULL, 'Små blanke røde jordbær med udpræget smag og duft. Remonterende; oplagt at afprøve til restaurantservering.', 'Kilde: https://www.johnnyseeds.com/fruits/strawberry/strawberry-bare-root-plants/mara-des-bois-spring-planted-strawberry-plants-5036.27.html'),
    ('Kinakål', 'Rubicon', 'Brassica rapa (Pekinensis Group)', 25, 30, 65, NULL, NULL, false, true, 'Navngiven kinakål til faste, aflange hoveder. Tjek leverandørens sortsspecifikke resistens og sæson før større indkøb.', 'Kilde: https://www.aeseeds.com/rubicon-f1-chinese-cabbage-seed/'),
    ('Koriander', 'Calypso', 'Coriandrum sativum', NULL, 5, NULL, NULL, 3, false, true, 'Meget langsom til at gå i stok ifølge leverandørens forsøg; fyldige planter til bladhøst.', 'Høstform: Løbende høst | Udplantning/timing: Udplantning | Kilde: https://www.johnnyseeds.com/herbs/cilantro-coriander/calypso-cilantro-coriander-seed-3803.html'),
    ('Majroe', 'Hakurei', 'Brassica rapa (Rapa Group)', NULL, 15, 40, NULL, 3, false, true, 'Hvid, fladrund salatmajroe; høstes ung for saftigt, mørt kød og sød, frugtig smag også rå.', 'Perkins: Direkte såning i 6 rækker er også mulig; senere foretrak han udplantning. | Høstform: Små knolde med eller uden blade | Udplantning/timing: Start: 11. april; Så/plant: 2. maj | Kilde: https://www.johnnyseeds.com/vegetables/turnips/hakurei-f1-turnip-seed-706.html'),
    ('Majroe', 'Nisseko', 'Brassica rapa (Rapa Group)', NULL, 15, 40, NULL, 3, false, true, NULL, 'Perkins: Direkte såning i 6 rækker er også mulig; senere foretrak han udplantning. | Høstform: Små knolde med eller uden blade | Udplantning/timing: Udplantning'),
    ('Majroe', 'Purple Top', 'Brassica rapa (Rapa Group)', NULL, 15, 40, NULL, 3, false, true, NULL, 'Perkins: Direkte såning i 6 rækker er også mulig; senere foretrak han udplantning. | Høstform: Små knolde med eller uden blade | Udplantning/timing: Udplantning'),
    ('Majroe', 'Scarlet Queen', 'Brassica rapa (Rapa Group)', NULL, 15, 40, NULL, 3, false, true, NULL, 'Perkins: Direkte såning i 6 rækker er også mulig; senere foretrak han udplantning. | Høstform: Små knolde med eller uden blade | Udplantning/timing: Udplantning'),
    ('Mizuna', 'Mizuna', 'Brassica rapa (Japonica Group)', 10, 5.08, NULL, 40, NULL, true, false, 'Dybt fligede blade med let sennepspræg; kan høstes som spæde blade i salatblandinger.', 'Kilde: https://www.johnnyseeds.com/vegetables/greens/asian-greens/mizuna-organic-asian-green-seed-2883.html'),
    ('Morgenfrue', 'Alpha', 'Calendula officinalis', NULL, 10, NULL, NULL, NULL, false, true, 'Klart orange blomster med spiselige kronblade; syrlig og let bitter note til salat og pynt.', 'Kilde: https://www.johnnyseeds.com/herbs/calendula/alpha-organic-calendula-seed-2935.html'),
    ('Mynthe', 'Maroc', 'Mentha spicata', NULL, 30, NULL, NULL, NULL, NULL, NULL, 'Marokkansk grøn mynte med tydelig myntearoma; flerårig og bredtvoksende. Start med få planter.', 'Kilde: https://www.rhs.org.uk/plants/369463/mentha-spicata-maroc/details'),
    ('Pak choi', 'Black Summer', 'Brassica rapa (Chinensis Group)', 25, 30, 45, NULL, NULL, false, true, 'Mørkegrønne ovale blade og brede lysegrønne stilke; kan høstes som mini eller fuld størrelse.', 'Kilde: https://www.johnnyseeds.com/vegetables/greens/pac-choi-bok-choy/black-summer-f1-green-seed-2460.53.html'),
    ('Pastinak', 'Javelin F1', 'Pastinaca sativa', 10, 10, NULL, 110, NULL, NULL, NULL, 'Slanke, glatte, tilspidsede rødder med god markmodstand mod kræft; egnet til overvintring ifølge leverandøren.', 'Kilde: https://www.johnnyseeds.com/vegetables/parsnips/javelin-f1-parsnip-seed-2028.84.html'),
    ('Peberfrugt', 'Carmen F1', 'Capsicum annuum', NULL, 40, 70, NULL, NULL, NULL, NULL, 'Lang konisk sød peber (Corno di Toro-type), der modner rød. Farverne i BC-købene er ikke i sig selv sortsnavne.', 'Kilde: https://www.johnnyseeds.com/vegetables/peppers/sweet-peppers/carmen-f1-corno-di-toro-pepper-seed-2993.54.html'),
    ('Persille', 'Darki', 'Petroselinum crispum', NULL, 5, NULL, NULL, 3, false, true, NULL, 'Høstform: Løbende høst | Udplantning/timing: Start: 10. april; Så/plant: 1. maj'),
    ('Persille', 'Darki Green', 'Petroselinum crispum', NULL, 5, NULL, NULL, 3, false, true, 'Mørkegrøn kruspersille; leverandøren kalder denne sort Darki Green. Den eksisterende “Darki” er ikke automatisk samme sort.', 'Høstform: Løbende høst | Udplantning/timing: Start: 10. april; Så/plant: 1. maj | Kilde: https://www.johnnyseeds.com/herbs/parsley/leaf-parsley/darki-green-parsley-seed-3513.30.html'),
    ('Rabarber', 'Victoria', 'Rheum × hybridum', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Navngiven rabarbersort til sammenligning af stængelfarve og syre. Planlæg med kroner/planter frem for frøgram.', 'Kilde: https://www.rhs.org.uk/plants/70672/rheum-hybridum-victoria/details'),
    ('Radise', 'Amythyst?', 'Raphanus sativus', 10, 5.08, NULL, 25, NULL, true, false, NULL, 'Høstform: Primært forår og efterår | Udplantning/timing: Direkte såning'),
    ('Radise', 'Bacchus', 'Raphanus sativus', 10, 5.08, NULL, 25, NULL, true, false, 'Lilla rund radise til kontrast i salat og tallerken. Høst ung og prøv skarphed lokalt.', 'Høstform: Primært forår og efterår | Udplantning/timing: Direkte såning | Kilde: https://www.johnnyseeds.com/vegetables/radishes/round-radishes/bacchus-f1-radish-seed-3675.html'),
    ('Radise', 'Crunchy King', 'Raphanus sativus', 10, 5.08, NULL, 25, NULL, true, false, NULL, 'Høstform: Primært forår og efterår | Udplantning/timing: Direkte såning'),
    ('Radise', 'Nelson', 'Raphanus sativus', 10, 5.08, NULL, 25, NULL, true, false, NULL, 'Høstform: Primært forår og efterår | Udplantning/timing: Direkte såning'),
    ('Radise', 'Nero Tondo', 'Raphanus sativus', 10, 5.08, NULL, 25, NULL, true, false, NULL, 'Høstform: Primært forår og efterår | Udplantning/timing: Så/plant: 10. maj'),
    ('Radise', 'Ping Pong', 'Raphanus sativus', 10, 5.08, NULL, 25, NULL, true, false, NULL, 'Høstform: Primært forår og efterår | Udplantning/timing: Direkte såning'),
    ('Radise', 'Rover', 'Raphanus sativus', 10, 5.08, NULL, 25, NULL, true, false, NULL, 'Høstform: Primært forår og efterår | Udplantning/timing: Direkte såning'),
    ('Radise', 'Roxanne', 'Raphanus sativus', 10, 5.08, NULL, 25, NULL, true, false, NULL, 'Høstform: Primært forår og efterår | Udplantning/timing: Direkte såning'),
    ('Rucola', 'Astro', 'Eruca vesicaria', 10, 5.08, NULL, 30, NULL, true, false, 'Salatrucola med fligede grønne blade; god som babyblad til gentagne korte hold.', 'Kilde: https://www.johnnyseeds.com/vegetables/greens/arugula-roquette/astro-organic-salad-arugula-seed-2015G.30.html'),
    ('Rucola', 'Esmee', 'Eruca vesicaria', 10, 5.08, NULL, 30, NULL, true, false, NULL, NULL),
    ('Rødbede', 'Boldor', 'Beta vulgaris', 25, 7, 55, NULL, NULL, false, true, NULL, 'Høstform: Engangshøst, ca. 5–6 cm diameter | Udplantning/timing: Udplantning'),
    ('Rødbede', 'Bulls Blood', 'Beta vulgaris', 25, 7, 55, NULL, NULL, false, true, NULL, 'Høstform: Engangshøst, ca. 5–6 cm diameter | Udplantning/timing: Udplantning'),
    ('Rødbede', 'Chiogga', 'Beta vulgaris', 25, 7, 55, NULL, NULL, false, true, NULL, 'Høstform: Engangshøst, ca. 5–6 cm diameter | Udplantning/timing: Start: 24. april; Så/plant: 15. maj'),
    ('Rødbede', 'Chioggia Guardsmark', 'Beta vulgaris (Conditiva Group)', 25, 7, 55, NULL, NULL, false, true, 'Rødbede med tydelige rosa og hvide ringe i snit. En særskilt navngiven sort; ret ikke den eksisterende “Chiogga” uden at kende frøposen.', 'Høstform: Engangshøst, ca. 5–6 cm diameter | Udplantning/timing: Udplantning | Kilde: https://www.johnnyseeds.com/vegetables/beets/specialty-beets/chioggia-guardsmark-organic-beet-seed-25G.84.html'),
    ('Rødbede', 'Merlin', 'Beta vulgaris', 25, 7, 55, NULL, NULL, false, true, NULL, 'Høstform: Engangshøst, ca. 5–6 cm diameter | Udplantning/timing: Udplantning'),
    ('Rødbede', 'Moneta', 'Beta vulgaris', 25, 7, 55, NULL, NULL, false, true, NULL, 'Høstform: Engangshøst, ca. 5–6 cm diameter | Udplantning/timing: Udplantning'),
    ('Rødbede', 'Touchstone', 'Beta vulgaris', 25, 7, 55, NULL, NULL, false, true, NULL, 'Høstform: Engangshøst, ca. 5–6 cm diameter | Udplantning/timing: Udplantning'),
    ('Salat', 'Alkindis', 'Lactuca sativa', 25, 30, NULL, NULL, NULL, false, true, NULL, 'Høstform: Hele hoveder | Udplantning/timing: Udplantning'),
    ('Salat', 'Buttercrunch', 'Lactuca sativa', 25, 30, NULL, NULL, NULL, false, true, NULL, 'Høstform: Hele hoveder | Udplantning/timing: Udplantning'),
    ('Salat', 'Flashy Trout', 'Lactuca sativa', 25, 30, NULL, NULL, NULL, false, true, NULL, 'Høstform: Hele hoveder | Udplantning/timing: Udplantning'),
    ('Salat', 'Green Saladbowl', 'Lactuca sativa', 25, 30, NULL, NULL, NULL, false, true, NULL, 'Høstform: Hele hoveder | Udplantning/timing: Udplantning'),
    ('Salat', 'Red Lollo', 'Lactuca sativa', 25, 30, NULL, NULL, NULL, false, true, NULL, 'Høstform: Hele hoveder | Udplantning/timing: Udplantning'),
    ('Salat', 'Ridgeline', 'Lactuca sativa', 25, 30, NULL, NULL, NULL, false, true, NULL, 'Høstform: Hele hoveder | Udplantning/timing: Udplantning'),
    ('Salat', 'S Green Crisp', 'Lactuca sativa', 25, 30, NULL, NULL, NULL, false, true, NULL, 'Høstform: Hele hoveder | Udplantning/timing: Udplantning'),
    ('Salat', 'S Red Crisp', 'Lactuca sativa', 25, 30, NULL, NULL, NULL, false, true, NULL, 'Høstform: Hele hoveder | Udplantning/timing: Start: 29. marts; Så/plant: 19. april'),
    ('Salat', 'Salanova Green', 'Lactuca sativa', 25, 30, NULL, NULL, NULL, false, true, NULL, 'Høstform: Hele hoveder | Udplantning/timing: Udplantning'),
    ('Salat', 'Salanova Green Butter', 'Lactuca sativa', 25, 30, NULL, NULL, NULL, false, true, 'Grøn Salanova-type med små smørbløde blade og praktisk opskæring til salat. Må ikke forveksles med eksisterende “Salanova Green”.', 'Høstform: Hele hoveder | Udplantning/timing: Udplantning | Kilde: https://www.johnnyseeds.com/vegetables/lettuce/salanova-lettuce/higgs-salanova-green-butter-pelleted-lettuce-seed-3056JP.html'),
    ('Salat', 'Salanova Red', 'Lactuca sativa', 25, 30, NULL, NULL, NULL, false, true, NULL, 'Høstform: Hele hoveder | Udplantning/timing: Udplantning'),
    ('Salat', 'Sparx', 'Lactuca sativa', 25, 30, NULL, NULL, NULL, false, true, NULL, 'Høstform: Hele hoveder | Udplantning/timing: Udplantning'),
    ('Salat', 'Trout Back', 'Lactuca sativa', 25, 30, NULL, NULL, NULL, false, true, NULL, 'Høstform: Hele hoveder | Udplantning/timing: Udplantning'),
    ('Salat', 'Truchas', 'Lactuca sativa', 25, 30, NULL, NULL, NULL, false, true, NULL, 'Høstform: Hele hoveder | Udplantning/timing: Udplantning'),
    ('Salat', 'All Star', 'Flere arter; afhænger af blanding', 10, 5.08, NULL, 42, NULL, true, false, 'Sammensat salatmix til mange bladformer og farver. Leverandørens Allstar Gourmet er en mulig sammenligning, ikke dokumenteret identisk blanding.', 'Høstform: 2–3 snit i gode forhold | Udplantning/timing: Så/plant: 1. maj | Kilde: https://www.johnnyseeds.com/vegetables/lettuce/lettuce-mixes/allstar-gourmet-lettuce-mix-vegetable-seed-2301.11.html'),
    ('Sennep (bladsennep)', 'Red Giant', 'Brassica juncea', 10, 5.08, NULL, 40, NULL, true, false, 'Brede grønne blade med rødlilla toner og tydelig sennepsstyrke; høstes spæd for mildere salatblad.', 'Kilde: https://www.johnnyseeds.com/vegetables/greens/mustard-greens/red-giant-mustard-green-seed-378.30.html'),
    ('Sennep (bladsennep)', 'Scarlet Frills', 'Brassica juncea', 10, 5.08, NULL, 40, NULL, true, false, NULL, NULL),
    ('Hvidkål', 'Caraflex F1', 'Brassica oleracea (Capitata Group)', 25, 30, NULL, NULL, NULL, false, true, 'Spidskål med lange slanke spidse hoveder; en konkret sort til sammenligning med BC’s generiske spidskål.', 'Høstform: Hele hoveder | Udplantning/timing: Udplantning | Kilde: https://www.johnnyseeds.com/vegetables/cabbage/fresh-market-cabbage/caraflex-f1-cabbage-seed-109.11.html'),
    ('Spinat', 'Flamingo', 'Spinacia oleracea', 15, 15, 40, NULL, 3, false, true, NULL, 'Høstform: Flere høst af blade | Udplantning/timing: Udplantning'),
    ('Spinat', 'Red Kitten', 'Spinacia oleracea', 15, 15, 40, NULL, 3, false, true, NULL, 'Høstform: Flere høst af blade | Udplantning/timing: Udplantning'),
    ('Spinat', 'Seaside', 'Spinacia oleracea', 15, 15, 40, NULL, 3, false, true, NULL, 'Høstform: Flere høst af blade | Udplantning/timing: Start: 22. marts; Så/plant: 12. april'),
    ('Spinat', 'Space', 'Spinacia oleracea', 15, 15, 40, NULL, 3, false, true, 'Glatbladet spinat; en navngiven sort til sammenligning med Seaside, som også kan høstes som babyspinat.', 'Høstform: Flere høst af blade | Udplantning/timing: Udplantning | Kilde: https://www.johnnyseeds.com/vegetables/spinach/smooth-leaf-spinach/space-f1-spinach-seed-644.54.html'),
    ('Kapucinerkarse', 'Alaska Mix', 'Tropaeolum majus', NULL, 10, NULL, NULL, 3, false, true, 'Broget løv og blomster i gule, orange og røde toner; både blomster og blade kan spises og har peberagtig smag.', 'Høstform: Løbende blomster | Udplantning/timing: Udplantning | Kilde: https://www.johnnyseeds.com/flowers/nasturtium/alaska-mix-nasturtium-seed-1202.26.html'),
    ('Squash/Zucchini', 'Dunja', 'Cucurbita pepo', NULL, 60, 50, NULL, NULL, false, true, 'Mørkegrøn zucchini af en navngiven sort; hyppig høst af unge frugter giver ensartet restaurantstørrelse.', 'Kilde: https://www.johnnyseeds.com/vegetables/squash/summer-squash/dunja-organic-f1-zucchini-squash-seed-3843G.56.html'),
    ('Squash/Zucchini', 'Sunburst', 'Cucurbita pepo', NULL, 60, 50, NULL, NULL, false, true, NULL, NULL),
    ('Timian', 'Summer Thyme', 'Thymus vulgaris', NULL, 20, NULL, NULL, NULL, NULL, NULL, 'Klassisk aromatisk kryddertimian. Langsigtet planteantal og høstmængder bør bygges på egne klip.', 'Kilde: https://www.plantetorvet.dk/p/96758/dyrk-selv-froe-oeko-timian-summer-thyme-thymus-vulgaris-l-summer-thyme'),
    ('Tomat', 'Estimo', 'Solanum sp. (grundstammens afstamning ikke verificeret)', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Podningsgrundstamme, ikke en frugtsort — dyrkes ikke for egne frugter. Perkins: Podningsgrundstamme, ikke dyrket for frugterne.'),
    ('Tomat', 'Ildi', 'Solanum lycopersicum', NULL, 22, 70, NULL, NULL, false, true, 'Gule små pæreformede tomater i lange hængende klaser; et visuelt anderledes valg til servering.', 'Perkins: Rigtbærende; billedtekst angiver 7–8 klaser med over 80 frugter i hver. | Høstform: Løbende plukning | Udplantning/timing: Plant efter nattefrost | Kilde: https://www.rhs.org.uk/plants/221555/lycopersicon-esculentum-ildi/details'),
    ('Æble', 'Red Aroma', 'Malus domestica', 400, 350, NULL, NULL, NULL, NULL, NULL, 'Saftigt nordisk æble med syrlig-sød smag; rød mutation af Aroma. Frugttræer kræver eget areal- og podningsgrundlag.', 'Kilde: https://www.sonneruplund.dk/eng/html/Aroma.html'),
    ('Ært', 'Sugar Ann', 'Pisum sativum', NULL, 1, NULL, NULL, NULL, true, false, 'Navngiven sukkerært med spiselige bælge; den eksisterende “Sugarsnap” betegner en type og er ikke nødvendigvis denne sort.', 'Perkins: Klatrestøtte; 1–2 cm i rækken. Kan undersås. | Høstform: Pluk hver 2.–3. dag | Udplantning/timing: Sås i kølig jord | Kilde: https://www.johnnyseeds.com/vegetables/peas/snap-peas/sugar-ann-pea-seed-559.html'),
    ('Ært', 'Sugarsnap', 'Pisum sativum', NULL, 1, NULL, NULL, NULL, true, false, NULL, 'Perkins: Klatrestøtte; 1–2 cm i rækken. Kan undersås. | Høstform: Pluk hver 2.–3. dag | Udplantning/timing: Sås i kølig jord'),
    ('Ært', 'Field Pea', 'Pisum sativum', 10, 2, NULL, NULL, NULL, NULL, NULL, 'Markært dyrket til spæde skud med mild ærtesmag; så tæt i bakke og høst typisk ved 7–13 cm.', 'Kilde: https://www.johnnyseeds.com/vegetables/shoots/pea-field-organic-shoot-seed-3161SG.html')
) AS vv(species_name, variety_name, latin, row_sp, plant_sp, days_t, days_d, weeks_tp, direct_sow, indoor_prop, descr, care)
LEFT JOIN new_species ns ON vv.species_name = ns.name_da
LEFT JOIN crop_species es ON vv.species_name = es.name_da;

COMMIT;